### ISSUE TITLE
Texworks 0.6.1

### ISSUE THREAD

**Issue by Patrick2776** [cdevalland/cmathluatex#6]
Bonjour, il semble qu'avec la version 0.61 de Texworks, on ne puisse plus utiliser lpeg.dll que vous avez compilé pour lua5.2 alors que le nouveau Texworks utilise lua 5.3.
Avez vous remarqué ce problème ?  Avez -vous une solution ? 
Merci 

PS: Encore merci pour cet outil bien pratique.

**Comment by cdevalland** [comment]
Bonjour,
je suis sous linux donc je n'ai pas ce souci.
Je vais contacter les développeurs de texworks pour voir s'ils peuvent
actualiser la librairie lpeg.

**Comment by cdevalland** [comment]
Aucune réponse à ma demande depuis juin.
Par contre, j'ai mis dans mon dépôt la dernière version de texworks pour windows qui fonctionne avec la librairie lpeg.
Faites un "download zip" pour la récupérer.
