### ISSUE TITLE
Archlinux et texworks 0.6.1

### ISSUE THREAD

**Issue by Patrick2776** [cdevalland/cmathluatex#7]
Bonjour, sous archlinux pour activer les scripts lua il faut mettre dans le fichier .bashrc la ligne suivante:

 export TW_PLUGINPATH=/usr/lib/texworks

Ceci semble être du à un bug de la version 0.6.1 de texworks qui n'est pas encore corrigé. Texworks ne trouvant pas le chemin menant au plugin lua et python.

Cordialement

**Comment by cdevalland** [comment]
Merci pour l'info.
